### ISSUE TITLE
unused arguments in your example

### ISSUE THREAD

**Issue by 2020new** [shosaco/vistime#18]
Thank you for this package ! 
Try to conduct the following example: 
pres <- data.frame(Position = rep(c("President", "Vice"), each = 3),
                   Name = c("Washington", rep(c("Adams", "Jefferson"), 2), "Burr"),
                   start = c("1789-03-29", "1797-02-03", "1801-02-03"),
                   end = c("1797-02-03", "1801-02-03", "1809-02-03"),
                   color = c('#cbb69d', '#603913', '#c69c6e'),
                   fontcolor = c("black", "white", "black"))

vistime(pres, col.event = "Position", col.group = "Name", title = "Presidents of the USA")  and got  

Fehler in vistime::vistime(pres, col.event = "Position", col.group = "Name",  : 
  unbenutzte Argumente (col.event = "Position", col.group = "Name")

**Comment by shosaco** [comment]
That's just for the development version. In the CRAN version, these arguments were not implented yet.

Use `devtools::install_github("shosaco/vistime")` to install the development version.
