### ISSUE TITLE
Adding a legend when using gg_vistime

### ISSUE THREAD

**Issue by julianmarenz** [shosaco/vistime#21]
Hi!

I am currently using the (great) vistime package to visualize the availability of data during certain periods of time, and their unavailability during others. To do so, I use a green shade when it is available, and a red shade when it is unavailable. Given that there are 22 groups, and sometimes available/NA changes fairly frequently, I was wondering whether there is any way to add a legend to the gg_vistime object that indicates on the side green = available, red = NA? Then there would not be a need to overload the bars themselves with text.

**Comment by shosaco** [comment]
I agree that would be a good addition to gg_vistime, unfortunately I don't have a handy solution at the moment...

**Comment by shosaco** [comment]
There is one implementation of a legend: https://github.com/wlhamilton/Patient-ward-movement-timelines

**Comment by shawnmceachin** [comment]
I just ran into this issue and found a workaround. First, make a "dummy" plot with the same data that goes into your gg_vistime plot (I used geom_bar) - it doesn't matter how this dummy plot looks, all you need is the legend from it. Once the legend is properly formatted, use get_legend (from ggpubr) to extract the legend from the dummy plot. Finally, use ggarrange (also from ggpubr) to combine your gg_vistime and your extracted legend.

library(vistime)
library(ggplot2)
library(ggpubr)
- create your vistime plot
p <- gg_vistime(dat)
- create your dummy plot; specify your x and y axes and the group used to create the fill
- scale_fill_manual allows you to customize the legend
dummy <- ggplot(data=dat, aes(x,y,fill)) + geom_bar(stat="identity") + scale_fill_manual()
- extract the legend from the dummy plot
leg <- get_legend(dummy ) 
- arrange them together
ggarrange(p, legend.grob = leg, position = "right") # it defaults to legend on top, so specify legend position if you want
