### ISSUE TITLE
Plot Conflict Issue 

### ISSUE THREAD

**Issue by ElhamAbiri** [shosaco/vistime#22]
Hi, 
Vistime is really great, thank you!

I found one issue when events are nested (i.e, a range is completely inside another range) in which the vistime doesn't allocate different rows when plotting them, so events will be plotted on top of each other (when `optimize_y = TRUE`). 

Looking at your `set_y_values.R` code, I think if we change *case2* condition as below, it will fix the conflict issue:

`toAdd$start >= all_on_current_y[j,"start"] & toAdd$start <= all_on_current_y[j,"end"]`

It will be great if you can update it or let me know if I'm missing anything.

Thanks,
Elham

![Data](https://user-images.githubusercontent.com/54553138/102563719-c20b8280-408e-11eb-8364-291ea5b249a0.PNG)
![Graph](https://user-images.githubusercontent.com/54553138/102563720-c2a41900-408e-11eb-97fd-6f2916cd837c.PNG)

**Comment by shosaco** [comment]
Thanks! Fixed in 179e479 by splitting up case 4. (Case 2 is for events).
