### ISSUE TITLE
Changing event label text size with gg_timevis

### ISSUE THREAD

**Issue by bmait101** [shosaco/vistime#25]
From reading old issues and combing the functions, am I correct that there is no way to change the text size of the labels for events inside the boxes? This is doable usable the plotly version, but not gg version... Any help much appreciated.

**Comment by shosaco** [comment]
Hi @bmait101 

correct! Tried with

```
library(ggplot2)
library(vistime)

timeline_data <- data.frame(event = c("Event 1", "Event 2"),
                            start = c("2020-06-06", "2020-10-01"), 
                            end   = c("2020-10-01", "2020-12-31"),
                            group = "My Events")

p <- gg_vistime(timeline_data) 
str(p)
```

but didn't find a solution to manipulate the `p` object in a proper way to change event text size.

best regards
sandro

**Comment by gmhhope** [comment]
That is such a pity! Please see if there is anything you guys can hlep with this. WIthout the function the change text size, it is not that useful with ggvistime than plotly version. However, I do want to have vector-based image from ggvistime. So embarassed!
