### ISSUE TITLE
Removal from CRAN?

### ISSUE THREAD

**Issue by mskyttner** [shosaco/vistime#32]
Thanks for a nice package!

It seems [here](https://cran.r-project.org/web/packages/vistime/index.html) that it was removed from CRAN due to "vistime-package.html:23:4: Warning: <img> attribute "align" not allowed for HTML5 " a NOTE?

Any plans of fixing it?

Would be nice to be able to depend on it!

**Comment by shosaco** [comment]
Hi!

thanks for the note, I re-submitted the package to CRAN and am waiting for the approval.

All the best
sandro

**Comment by shosaco** [comment]
@mskyttner fixed: https://cran.r-project.org/web//packages/vistime/index.html

**Comment by mskyttner** [comment]
Nice! Thanks! :)
