### ISSUE TITLE
vistime package not on CRAN

### ISSUE THREAD

**Issue by shahronak47** [shosaco/vistime#35]
Hi, the package has been removed from CRAN.  https://cran.r-project.org/web/packages/vistime/index.html 

<img width="716" alt="image" src="https://github.com/shosaco/vistime/assets/10164875/067d7f4a-40ab-4c42-8282-ebd1e91e1c06">

**Comment by dan-aridhia** [comment]
The root cause appears to be failing checks for the assertive.properties package (another archived package required by assertive.types, [issue](https://bitbucket.org/richierocks/assertive/issues/265/assertiveproperties-has-been-archived)).

**Comment by shosaco** [comment]
Thanks @dan-aridhia and @shahronak47, fixed the issue and resubmitted the package. It's on CRAN again.
