### ISSUE TITLE
Reordering the bars

### ISSUE THREAD

**Issue by semenoffalex** [shosaco/vistime#9]
Thanks for a great package. 

Is there a way to arrange the order of bars by start date or any other column of the data.frame or at least preserve the original order from the data.frame?

**Comment by shosaco** [comment]
Right now the bars are ordered automatically to optimize y-space. I could add a switch for that to only optimize y-axis if switch is TRUE and leave the order as given in the input-data otherwise.

**Comment by shosaco** [comment]
Added a new argument `optimize_y` to the function. Use `optimize_y = FALSE` to use the order of the input data. Does this fix your problem? Try it out using `devtools::install_github("shosaco/vistime")`. @semenoffalex

**Comment by semenoffalex** [comment]
Great, it did the job! Thank you.
